### ISSUE TITLE
Can't detect provider on Android Metamask browser

### ISSUE THREAD

**Issue by lucaskuan** [MetaMask/detect-provider#45]
Hi, I built a DAPP with React and React router but I got problem on Android Metamask browser only.

When the page is loaded directly from the URL `https://example.com/mint` this library can't find any provider for my page.

However, this library will able to detect provider when I'm navigating from the main page `https://example.com` to `https://example.com/mint`

I hope someone has resolved this issue and is able to help out. Thanks in advance.

**Comment by mcmire** [comment]
Given that this problem only occurs when you change routes, this problem seems specific to your app. Is it possible to share the repo for your app? If not, can you make a sample repo on GitHub which demonstrates your issue and send us a link to that? Otherwise, it's a bit difficult to tell exactly why this is happening.

**Comment by lucaskuan** [comment]
Thanks for your reply, below is how my app looks like

```
// index.js


window.addEventListener('load', async () => {
  ReactDOM.render(
    <React.StrictMode>
      <BrowserRouter>
        <Main />
      </BrowserRouter>
    </React.StrictMode>,
    document.getElementById('root')
  );
});

// main.js

const Main = () => {
  return (
    <ThemeProvider theme={theme}>
      <div>
        <NavBar />
      </div>
      <Routes>
        <Route path="/" element={<App />} />
        <Route path="/mint" element={<Mint />} />
      </Routes>
    </ThemeProvider>
  );
}
```

Tried with react router v5 & v6, on react 17

**Comment by mcmire** [comment]
Okay — where are you using this library?

**Comment by lucaskuan** [comment]
This is how I make the call

```
  useEffect(() => {
    async function connect() {
      const provider = await detectEthereumProvider({ timeout: 10000 })

      if (provider) {
        setProvider(provider)
      } else {
        // setEthError('Non-Ethereum browser detected. You should consider trying MetaMask!')
      }
    }

    connect()
  }, [])
```

**Comment by lucaskuan** [comment]
@mcmire do you have any clue?

**Comment by mcmire** [comment]
@lucaskuan I'd have to set up a test app to verify this, so I'm not sure yet. If you can set up a repo that I can clone and run locally then that would be helpful! Otherwise I will take a look tomorrow :)

**Comment by mcmire** [comment]
Hi @lucaskuan, I made a test app to try to reproduce this error but was unable to. Here's the app if you want to play around with it: https://codesandbox.io/s/metamask-detect-provider-issue-45-repro-hi92h2. If you click on the Console tab in the preview pane you can see that it is calling `detectEthereumProvider` each time you switch routes without a hitch. Can you see if you can reproduce your issue here? You can make your own version by clicking on the "Fork" button.

**Comment by lucaskuan** [comment]
Thank you so much. Then I guess my project setup is a bit problematic. I
will investigate more.

**Comment by robotgame** [comment]
I am facing the same problem.

Something weird is that depending on where the app is hosted, I get different results. 
In my case, everything works fine on Netlify, but not on DigitalOcean.

Some users have reported that it doesn't work on either of them.

The one on DigitalOcean: https://yieldhunt.game/home
The one on Netlify: https://yieldhunt.netlify.app/home

**Comment by lucaskuan** [comment]
Yes, mine one is hosting on S3 as a static website. I wonder if it is
related to how the server serves the page.

**Comment by mcmire** [comment]
I'm going to close this as we aren't able to reproduce this issue. For anyone else coming across this, please make sure you are accessing your dapp _within the browser inside of the MetaMask mobile app_. I've explained why this is here: https://github.com/MetaMask/detect-provider/issues/38#issuecomment-1215739459

**Comment by lucaskuan** [comment]
Yes in useEffect
