### ISSUE TITLE
Unexpected behavior when there are multiple injected providers

### ISSUE THREAD

**Issue by zeosamaster** [MetaMask/detect-provider#53]
## Steps to reproduce
1. Install & setup MetaMask
2. Install & setup another injected wallet (e.g. CoinbaseWallet)
3. `const provider = await detectEthereumProvider({ mustBeMetaMask: true })`
4. `await provider.request({ method: 'eth_requestAccounts' })`

## Expected behavior
1. MetaMask wallet prompts for connection
2. CoinbaseWallet does not prompt for connection

## Actual behavior
1. MetaMask wallet prompts for connection
2. CoinbaseWallet prompts for connection

**Comment by GabrielBuragev** [comment]
Hey @zeosamaster i bumped into this issue and i think that is actually an expected behavior as both providers are stored in the `window.ethereum.providers`.
You can then filter out the provider you need and use it in your app. Check it out [here](https://docs.cloud.coinbase.com/wallet-sdk/docs/injected-provider-guidance).

While this is a fortunate case where Coinbase & MetaMask play good together (by storing both objects inside the `window.ethereum.providers` and lets you choose which one you use), there are cases where other wallet extensions simply overwrite the global `window.ethereum` object. 
I faced an issue where i had "Frame Companion" installed alongside MetaMask and Frame's extension simply overwrites the object which makes any app unusable(cannot detect MetaMask extension) ... 

I opened an [issue for this](https://github.com/MetaMask/detect-provider/issues/73) as i think this is the right approach so dapps can detect such cases and react (give users feedback that he has conflicting extensions installed).

For now, unfortunately, we cannot really act in such situations and i really hope we can at least get a rejection from the `await detectEthereumProvider({ mustBeMetaMask: true })` so we can handle these cases in our dapps.
